### PR TITLE
Animal name tweaks (closes #17)

### LINKED ISSUE #17: Animal name generator tweaks
Right now the animal name generator works, but 

- [ ] the sourcelist combines both male and female names in one file, so the names at times come out a combination of those. There should be separate source files for both sexes.

- [ ] the animals get surnames from the same sourcelist. They probably shouldn't even *have* surnames.

This is a simple change for someone with the workspace set up, I'm noting it down so it doesn't get forgotten.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47328106-animal-name-generator-tweaks?utm_campaign=plugin&utm_content=tracker%2F2771446&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2771446&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by aaron-harris**
In addition to the surface-level tweaks mentioned in #17 (no animal surnames, gendered animal names), I modified `CreatureAssetTheme` to allow for surname-less themes; its constructor now allows null to be passed in place of a prefab name as a signal to use an empty name generator that emits only the empty string.

### CODE REVIEW

**Comment by Cervator** [comment]
Hi @aaron-harris and thanks!

Have you tested this with Light & Shadow and/or WildAnimals to make sure they work as-is with this change included? Since the prefab name changes/splits I wonder if any modules depending on this will need matching changes to work.

**Comment by aaron-harris** [comment]
Not yet; I didn't know which modules I needed to look into.  (Is there a master dependency diagram somewhere?  That would be helpful!)  I'll check the ones you mentioned and get back to you.

**Comment by aaron-harris** [comment]
Okay, I've double-checked both `LightAndShadow` and `WildAnimals`, and everything seems fine.  More specifically:

* `LightAndShadow` only uses `NameGenerator` via `StaticCities`, for the city name, and I haven't touched that code.
* The prefabs for all of the `WildAnimals` deer flavors actually specify that they should have dwarven names.  I'm guessing they haven't been updated since the animal name generator was created.
* Just in case, I created a Light & Shadow world mixing in `WildAnimals` and spawned a deer.  I couldn't see its name, since the prefab doesn't give it a name plate, but nothing crashed.

**Comment by Cervator** [comment]
Belated thanks for the double checking! Finally had a chance to test this out and everything appears in good order. Merging and will add you to the game credits next I get a chance :-)

**Pull request merged**
